#!/usr/bin/env bash
# .codex/setup.sh — Codex Cloud container self-provisioning for adult-ai-app.
#
# Purpose: make DB / service / integration tasks dispatchable to Codex Cloud by
# building a self-contained offline environment — dependencies + local D1
# (miniflare) with all migrations applied + a minimal seed + placeholder secrets
# + a mock external-API server. NO external network, NO real API, NO real payment.
#
# Idempotent: safe to re-run.
#
# Knobs (all optional):
#   SKIP_INSTALL=1          skip `pnpm install` (deps already present)
#   WRANGLER_PERSIST_DIR=X  isolate local D1/R2/KV state under X (default: .wrangler)
#   START_MOCK=1            start .codex/mock-server.mjs in the background at the end
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# --- offline / CI guards (no telemetry, no auth prompts, no update checks) ---
export CI="${CI:-true}"
export WRANGLER_SEND_METRICS=false
export DO_NOT_TRACK=1
export npm_config_update_notifier=false

D1_DB_NAME="adult-ai-db"

# wrangler d1 --local writes to a local sqlite state dir. Optionally isolate it so
# a verification run does not touch a developer's existing .wrangler state.
PERSIST_ARGS=()
if [ -n "${WRANGLER_PERSIST_DIR:-}" ]; then
  mkdir -p "$WRANGLER_PERSIST_DIR"
  PERSIST_ARGS=(--persist-to "$WRANGLER_PERSIST_DIR")
fi

log() { printf '\n\033[1;36m[codex-setup]\033[0m %s\n' "$*"; }

# --- 1. toolchain: pin pnpm via corepack ---
log "toolchain: corepack + pnpm@9.15.0"
corepack enable >/dev/null 2>&1 || true
corepack prepare pnpm@9.15.0 --activate >/dev/null 2>&1 || true

# --- 2. dependencies ---
if [ "${SKIP_INSTALL:-0}" = "1" ]; then
  log "deps: SKIP_INSTALL=1 (skipping pnpm install)"
else
  log "deps: pnpm install --frozen-lockfile"
  pnpm install --frozen-lockfile
fi

# --- 3. placeholder secrets / env (.dev.vars is gitignored; never clobber a real one) ---
if [ -f .dev.vars ]; then
  log "env: .dev.vars already present — leaving it untouched"
else
  log "env: writing placeholder .dev.vars from .codex/dev-vars.example"
  cp .codex/dev-vars.example .dev.vars
fi

# --- 4. local D1 (miniflare) + migrations, autogenerate-first policy ---
# The committed drizzle/*.sql are drizzle-kit OUTPUT (autogenerated). We apply
# them to local miniflare state; no Cloudflare auth, fully offline.
# NEW schema changes MUST be produced with `pnpm db:generate` first (never hand-
# written) — see .codex/README.md.
log "db: apply migrations to LOCAL D1 (offline, no auth)"
pnpm exec wrangler d1 migrations apply "$D1_DB_NAME" --local "${PERSIST_ARGS[@]}"

# --- 5. minimal seed (full pnpm db:seed needs REMOTE R2 auth; we stay offline) ---
log "db: seed minimal data into LOCAL D1"
pnpm exec wrangler d1 execute "$D1_DB_NAME" --local "${PERSIST_ARGS[@]}" --file .codex/seed-min.sql

# --- 6. sanity: a DB-dependent query must return the seeded rows ---
log "verify: SELECT count(*) FROM character (LOCAL D1)"
pnpm exec wrangler d1 execute "$D1_DB_NAME" --local "${PERSIST_ARGS[@]}" \
  --command "SELECT count(*) AS characters, (SELECT count(*) FROM message) AS messages FROM character;"

# --- 7. optional: mock external-API server ---
if [ "${START_MOCK:-0}" = "1" ]; then
  log "mock: starting .codex/mock-server.mjs in background"
  node .codex/mock-server.mjs &
  sleep 1
fi

log "container provisioning complete."
log "mock external-API server (no network): node .codex/mock-server.mjs"
log "see .codex/README.md for the dispatchable task-class matrix."
