# ファイル変更ベースのラベル付け
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'doc/**/*'
          - '**/README*.md'

admin:
  - changed-files:
      - any-glob-to-any-file: 'admin/**/*'
