/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIdRouteImport } from './routes/chat/$id'
import { Route as ApiChatIdRouteImport } from './routes/api/chat/$id'
import { Route as ApiChatIdHistoryRouteImport } from './routes/api/chat/$id_/history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatIdRoute = ApiChatIdRouteImport.update({
  id: '/api/chat/$id',
  path: '/api/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatIdHistoryRoute = ApiChatIdHistoryRouteImport.update({
  id: '/api/chat/$id_/history',
  path: '/api/chat/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat/$id': typeof ChatIdRoute
  '/api/chat/$id': typeof ApiChatIdRoute
  '/api/chat/$id/history': typeof ApiChatIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat/$id': typeof ChatIdRoute
  '/api/chat/$id': typeof ApiChatIdRoute
  '/api/chat/$id/history': typeof ApiChatIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat/$id': typeof ChatIdRoute
  '/api/chat/$id': typeof ApiChatIdRoute
  '/api/chat/$id_/history': typeof ApiChatIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat/$id' | '/api/chat/$id' | '/api/chat/$id/history'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat/$id' | '/api/chat/$id' | '/api/chat/$id/history'
  id:
    | '__root__'
    | '/'
    | '/chat/$id'
    | '/api/chat/$id'
    | '/api/chat/$id_/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatIdRoute: typeof ChatIdRoute
  ApiChatIdRoute: typeof ApiChatIdRoute
  ApiChatIdHistoryRoute: typeof ApiChatIdHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/$id': {
      id: '/api/chat/$id'
      path: '/api/chat/$id'
      fullPath: '/api/chat/$id'
      preLoaderRoute: typeof ApiChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/$id_/history': {
      id: '/api/chat/$id_/history'
      path: '/api/chat/$id/history'
      fullPath: '/api/chat/$id/history'
      preLoaderRoute: typeof ApiChatIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatIdRoute: ChatIdRoute,
  ApiChatIdRoute: ApiChatIdRoute,
  ApiChatIdHistoryRoute: ApiChatIdHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
