#!/usr/bin/env tsx
/**
 * charap インポートキャラの system_prompt からメタノイズを除去し、
 * visual_prompt を image_meta から再構築する migration SQL を生成する。
 *
 * 使い方:
 *   npx tsx scripts/regenerate-character-prompts.ts
 *
 * 出力:
 *   drizzle/0015_strip_character_meta_noise.sql  — 本番 D1 適用用 UPDATE SQL
 *   drizzle/0014_refresh_adult_import_cards.sql  — ローカル seed (本番データを反映)
 *   /tmp/char-cleanup-report.txt                  — 処理件数・変更サマリ
 */

import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  cleanCharacterInfoText,
  getCharacterInfoQualityIssues,
} from "../src/lib/character-info-quality.ts";

const REPO_ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");

// ---- ノイズ除去ルール ----

const NOISE_LINE_PATTERNS = [
  /^出典:/,
  /^作者:/,
  /^★/,
  /^※.*(差分追加|時点|背景\d+|アンドロイド\d+|量産型|特別仕様)/,
  /^\[👤/,
  /スーパー\/ウルトラ\/ブースト\/プライム推奨/,
  /^\d+月\d+日:/,
] as const;

function stripNoise(text: string): string {
  return cleanCharacterInfoText(
    text
      .split("\n")
      .filter((line) => !NOISE_LINE_PATTERNS.some((p) => p.test(line)))
      .join("\n")
      .replace(/公開カードの雰囲気を保ち、?/g, "")
      .replace(/★[^\n。]*(?:。(?!\s)[^\n。]*)*。\s*/g, "")
      .replace(/特別仕様アンドロイド\d+。量産型アンドロイド\d+。背景\d+。?\s*/g, "")
      .replace(/、?※[^\n。]*差分追加[^\n。]*。?\s*/g, "")
      .replace(/\s*女神様]で[^\n。]*。\s*/g, " ")
      .replace(/\n{3,}/g, "\n\n")
      .trim(),
  );
}

// ---- SQL エスケープ ----

function sqlEscape(value: string): string {
  return value.replace(/'/g, "''");
}

// ---- image_meta → visual_prompt ----

interface ImageMeta {
  appearance?: string;
  artStyle?: string;
  outfit?: string;
  negativePrompt?: string;
}

const VISUAL_SUFFIX =
  " Atmospheric anime portrait, expressive eyes, polished mobile character-card illustration.";

function buildVisualFromMeta(imageMeta: ImageMeta | null | undefined): string | null {
  if (!imageMeta?.appearance) return null;
  const parts = [imageMeta.appearance, imageMeta.artStyle, imageMeta.outfit].filter(Boolean);
  return parts.join(", ") + VISUAL_SUFFIX;
}

// ---- D1 fetch ----

interface D1Row {
  id: string;
  user_id: string;
  name: string;
  avatar: string | null;
  system_prompt: string;
  visual_prompt: string | null;
  greeting: string | null;
  tags: string | null;
  created_at: number | null;
  image_meta: string | ImageMeta | null;
}

interface WranglerResult {
  results?: D1Row[];
}

function fetchFromD1(): D1Row[] {
  console.log("[fetch] wrangler d1 execute adult-ai-db --remote ...");
  const raw = execSync(
    `cd ${REPO_ROOT} && pnpm exec wrangler d1 execute adult-ai-db --remote ` +
      `--command="SELECT id, user_id, name, avatar, system_prompt, visual_prompt, greeting, tags, created_at, image_meta FROM character WHERE tags LIKE '%\\"imported\\"%' ORDER BY created_at;" ` +
      `--json`,
    { encoding: "utf8", maxBuffer: 50 * 1024 * 1024 },
  );
  const parsed = JSON.parse(raw) as WranglerResult[];
  const result = parsed[0]?.results;
  if (!Array.isArray(result)) {
    throw new Error("Unexpected D1 response shape: " + JSON.stringify(parsed).slice(0, 200));
  }
  console.log(`[fetch] got ${result.length} rows`);
  return result;
}

// ---- main ----

function main() {
  const rows = fetchFromD1();

  const sqlLines: string[] = [
    "-- Auto-generated by scripts/regenerate-character-prompts.ts",
    "-- Strips charap meta-noise from imported character prompts",
    "-- Apply: wrangler d1 execute adult-ai-db --remote --file=drizzle/0015_strip_character_meta_noise.sql",
    "",
  ];

  const reportLines: string[] = [`processed: ${rows.length} characters`, ""];

  let changed = 0;
  let qualityIssueCount = 0;

  for (const row of rows) {
    const qualityIssues = getCharacterInfoQualityIssues(row.system_prompt ?? "");
    if (qualityIssues.length > 0) qualityIssueCount++;
    const cleanedPrompt = stripNoise(row.system_prompt ?? "");

    const imageMeta: ImageMeta | null =
      typeof row.image_meta === "string"
        ? (JSON.parse(row.image_meta) as ImageMeta)
        : (row.image_meta ?? null);

    const newVisual = buildVisualFromMeta(imageMeta);

    const promptChanged = cleanedPrompt !== (row.system_prompt ?? "").trim();
    const visualChanged = newVisual !== row.visual_prompt;

    if (!promptChanged && !visualChanged) {
      reportLines.push(
        `${row.id}: no change quality=${qualityIssues.length > 0 ? qualityIssues.join(",") : "ok"}`,
      );
      continue;
    }

    changed++;

    const setClauses: string[] = [];
    if (promptChanged) {
      setClauses.push(`  system_prompt = '${sqlEscape(cleanedPrompt)}'`);
    }
    if (visualChanged) {
      if (newVisual === null) {
        setClauses.push(`  visual_prompt = NULL`);
      } else {
        setClauses.push(`  visual_prompt = '${sqlEscape(newVisual)}'`);
      }
    }

    sqlLines.push(
      `UPDATE character SET`,
      ...setClauses.map((c, i, arr) => c + (i < arr.length - 1 ? "," : "")),
      `WHERE id = '${sqlEscape(row.id)}';`,
      "",
    );

    reportLines.push(
      `${row.id}: prompt=${promptChanged ? "cleaned" : "unchanged"} visual=${visualChanged ? "rebuilt" : "unchanged"} quality=${qualityIssues.length > 0 ? qualityIssues.join(",") : "ok"}`,
    );
  }

  reportLines.push(
    "",
    `changed: ${changed}/${rows.length}`,
    `quality issues: ${qualityIssueCount}/${rows.length}`,
  );

  // ---- ローカル seed (0014) 再生成 ----
  // 本番の clean 済みデータをそのまま INSERT OR REPLACE に変換する
  const USER_ID = "sukererion@gmail.com";
  const seedLines: string[] = [
    "-- Auto-generated by scripts/regenerate-character-prompts.ts",
    "-- Source: production adult-ai-db D1 (clean state after 0015 migration)",
    "-- Replace: drizzle/0014_refresh_adult_import_cards.sql",
    "",
    `INSERT OR IGNORE INTO user (id, email, created_at) VALUES ('${USER_ID}', '${USER_ID}', 1778841327846);`,
    `DELETE FROM character WHERE user_id = '${USER_ID}' AND id LIKE 'import-%' AND tags LIKE '%"imported"%';`,
  ];

  for (const row of rows) {
    const cleanedPrompt = stripNoise(row.system_prompt ?? "");
    const imageMeta: ImageMeta | null =
      typeof row.image_meta === "string"
        ? (JSON.parse(row.image_meta) as ImageMeta)
        : (row.image_meta ?? null);
    const newVisual = buildVisualFromMeta(imageMeta);

    const id = sqlEscape(row.id);
    const userId = sqlEscape(row.user_id ?? USER_ID);
    const name = sqlEscape(row.name ?? "");
    const avatar = row.avatar ? `'${sqlEscape(row.avatar)}'` : "NULL";
    const prompt = sqlEscape(cleanedPrompt);
    const visual = newVisual ? `'${sqlEscape(newVisual)}'` : "NULL";
    const greeting = row.greeting ? `'${sqlEscape(row.greeting)}'` : "NULL";
    const tags = row.tags ? `'${sqlEscape(row.tags)}'` : "NULL";
    const createdAt = row.created_at ?? 1778841327846;

    seedLines.push(
      `INSERT OR REPLACE INTO character (id, user_id, name, avatar, system_prompt, visual_prompt, greeting, tags, created_at) VALUES ('${id}', '${userId}', '${name}', ${avatar}, '${prompt}', ${visual}, ${greeting}, ${tags}, ${createdAt});`,
    );
  }

  const seedOut = join(REPO_ROOT, "drizzle/0014_refresh_adult_import_cards.sql");
  writeFileSync(seedOut, seedLines.join("\n") + "\n");
  console.log(`[done] Seed written: ${seedOut} (${rows.length} characters)`);

  const sqlOut = join(REPO_ROOT, "drizzle/0015_strip_character_meta_noise.sql");
  const reportOut = "/tmp/char-cleanup-report.txt";

  writeFileSync(sqlOut, sqlLines.join("\n") + "\n");
  writeFileSync(reportOut, reportLines.join("\n") + "\n");

  console.log(`[done] SQL written: ${sqlOut}`);
  console.log(`[done] Report written: ${reportOut}`);
  console.log(`[done] ${changed}/${rows.length} characters updated`);

  // sanity check
  const sqlContent = sqlLines.join("\n");
  const seedContent = seedLines.join("\n");
  const residualShutten =
    (sqlContent.match(/出典:/g) ?? []).length + (seedContent.match(/出典:/g) ?? []).length;
  const residualSakusha =
    (sqlContent.match(/作者:/g) ?? []).length + (seedContent.match(/作者:/g) ?? []).length;
  if (residualShutten > 0 || residualSakusha > 0) {
    console.error(`[FAIL] residual noise: 出典=${residualShutten} 作者=${residualSakusha}`);
    process.exit(1);
  }
  console.log("[verify] 出典: 0, 作者: 0 — clean");
}

main();
