INSERT INTO scene_location (id, name_jp, created_at) VALUES
('bedroom','寝室',0),
('hotel_room','ホテルの部屋',0),
('classroom','教室',0),
('office','オフィス',0),
('bathroom','浴室',0),
('car_interior','車内',0),
('park','公園',0),
('library','図書館',0),
('cafe','カフェ',0),
('living_room','リビング',0),
('kitchen','キッチン',0),
('gym','ジム',0),
('pool','プール',0),
('beach','ビーチ',0),
('rooftop','屋上',0),
('hospital_room','病室',0),
('train','電車内',0),
('elevator','エレベーター',0),
('closet','クローゼット',0),
('balcony','バルコニー',0),
('night_bus','夜行バス車内',0);

INSERT INTO scene_location_tag (location_id, tag) VALUES
('bedroom','bed'),('bedroom','indoors'),
('hotel_room','hotel room'),('hotel_room','bed'),('hotel_room','indoors'),
('classroom','classroom'),('classroom','desk'),('classroom','school'),
('office','office'),('office','desk'),('office','indoors'),
('bathroom','bathroom'),('bathroom','bathtub'),
('car_interior','car interior'),('car_interior','seat'),
('park','park'),('park','grass'),('park','outdoors'),
('library','library'),('library','bookshelf'),
('cafe','cafe'),('cafe','table'),('cafe','indoors'),
('living_room','living room'),('living_room','sofa'),
('kitchen','kitchen'),('kitchen','counter'),
('gym','gym'),('gym','equipment'),
('pool','swimming pool'),('pool','water'),('pool','outdoors'),
('beach','beach'),('beach','sand'),('beach','sea'),('beach','outdoors'),
('rooftop','rooftop'),('rooftop','city'),('rooftop','outdoors'),('rooftop','night'),
('hospital_room','hospital room'),('hospital_room','bed'),
('train','train interior'),('train','seat'),
('elevator','elevator'),('elevator','mirror'),
('closet','closet'),('closet','indoors'),
('balcony','balcony'),('balcony','outdoors'),('balcony','night'),
('night_bus','intercity bus interior'),('night_bus','reclining seat'),('night_bus','dim lighting'),('night_bus','night'),('night_bus','window'),('night_bus','indoors');
